# Generated by Django 5.2.6 on 2025-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bookingpayment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpayment',
            name='provider_order_id',
        ),
        migrations.RemoveField(
            model_name='bookingpayment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='bookingpayment',
            name='url',
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='gateway_order_id',
            field=models.CharField(blank=True, help_text='Order ID or reference from gateway', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, help_text='Payment ID from gateway (e.g. Razorpay payment ID)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Raw gateway response payload for audits and reconciliation', null=True),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Payment link generated for the customer.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
