# Generated by Django 5.2.6 on 2025-10-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_bookingpayment_provider_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpayment',
            name='file_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
