# Generated by Django 5.2.6 on 2025-11-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='mobile',
            field=models.CharField(db_index=True, default=8004349271, max_length=15),
            preserve_default=False,
        ),
    ]
