# Generated by Django 5.2.6 on 2025-11-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
