# Generated by Django 5.2.6 on 2025-12-17 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_otp_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Manager / parent user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, db_index=True, help_text='External / third-party user ID (agents only)', max_length=50, null=True, unique=True),
        ),
    ]
