# Generated by Django 5.2.6 on 2025-12-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_parent_user_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='view_all',
            field=models.BooleanField(default=False, help_text='If true, users with this role can view all records'),
        ),
    ]
