# Generated by Django 5.2.6 on 2025-12-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_role_view_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='List of permission keys'),
        ),
    ]
