# Generated by Django 5.2.6 on 2025-12-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='max_amount',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='role',
            name='max_percentage',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
