# Generated by Django 5.2.6 on 2025-12-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_role_max_amount_role_max_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custome_permissions',
            field=models.JSONField(blank=True, default=list, help_text='List of permission keys'),
        ),
    ]
