# Generated by Django 5.2.6 on 2026-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_custome_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mpin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
