# Generated by Django 5.2.6 on 2026-01-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_olddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olddata',
            name='mobile',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
