# Generated by Django 5.2.6 on 2025-09-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('test', 'Lab Test'), ('profile', 'Profile'), ('package', 'Package')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sample_required', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'test'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='lab.labcategory')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='content_management.contentmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'profile'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='lab.labcategory')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='content_management.contentmanager')),
                ('tests', models.ManyToManyField(related_name='profiles', to='lab.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'package'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='lab.labcategory')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='content_management.contentmanager')),
                ('tests', models.ManyToManyField(blank=True, related_name='packages', to='lab.labtest')),
                ('profiles', models.ManyToManyField(blank=True, related_name='packages', to='lab.profile')),
            ],
        ),
    ]
