# Generated by Django 5.2.6 on 2025-09-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_labtest_description_labtest_investigation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='investigation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='sample_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
