# Generated by Django 5.2.6 on 2025-09-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_labtest_investigation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcategory',
            name='entity_type',
            field=models.CharField(choices=[('lab_test', 'Lab Test'), ('profile', 'Profile'), ('package', 'Package')], max_length=50),
        ),
    ]
