# Generated by Django 5.2.6 on 2025-11-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_labcategory_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
