# Generated by Django 5.2.6 on 2025-11-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_labtest_is_featured_package_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
