# Generated by Django 5.2.6 on 2025-11-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_package_offer_price_profile_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='image',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='sample_required',
        ),
        migrations.AddField(
            model_name='labtest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='temperature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
