# Generated by Django 5.2.6 on 2025-12-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_remove_labtest_image_remove_labtest_investigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='child_tests',
            field=models.JSONField(blank=True, default=list, help_text='List of child tests'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
