# Generated by Django 5.2.6 on 2025-12-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_labtest_child_tests_labtest_test_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='test_count',
        ),
    ]
