# Generated by Django 5.2.6 on 2025-12-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_remove_labtest_test_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'lab_test'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='lab.labcategory'),
        ),
    ]
