# Generated by Django 5.2.6 on 2025-10-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmanager',
            name='file',
        ),
        migrations.AddField(
            model_name='contentmanager',
            name='file_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
