# Generated by Django 5.2.6 on 2025-10-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_admin_discount_booking_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingactiontracker',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('item_update', 'Item Updated'), ('status_change', 'Status Change'), ('payment_update', 'Payment Update'), ('add_item', 'Item Added'), ('remove_item', 'Item Removed'), ('cancel', 'Cancelled'), ('other', 'Other')], max_length=50),
        ),
    ]
