# Generated by Django 5.2.6 on 2025-10-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookingactiontracker_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('payu', 'PayU'), ('cash', 'Cash on Delivery'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
