# Generated by Django 5.2.6 on 2025-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online'), ('upi', 'UPI'), ('card', 'Card'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
