# Generated by Django 5.2.6 on 2025-10-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ref_id',
            field=models.CharField(blank=True, help_text='Human-readable reference ID (e.g., DP2510080001)', max_length=20, null=True, unique=True),
        ),
    ]
