# Generated by Django 5.2.6 on 2025-10-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('verified', 'Verified'), ('sample_collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('report_uploaded', 'Report Uploaded'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registered', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('verified', 'Verified'), ('sample_collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('report_uploaded', 'Report Uploaded'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=30),
        ),
    ]
