# Generated by Django 5.2.6 on 2025-10-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_customer_status_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_status',
            field=models.CharField(choices=[('registered', 'Registered'), ('verified', 'Verified'), ('payment_collected', 'Payment Collected'), ('sample_collected', 'Sample Collected'), ('report_uploaded', 'Report Uploaded'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='registered', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('verified', 'Verified'), ('manger_assigned', 'Manger Assigned'), ('feild_agent_assigned', 'Feild Agent Assigned'), ('payment_collected', 'Payment Collected'), ('sample_collected', 'Sample Collected'), ('report_uploaded', 'Report Uploaded'), ('health_manger_assigned', 'Health Manger Assigned'), ('dietitian_assigned', 'Dietitian Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=30),
        ),
    ]
