# Generated by Django 5.2.6 on 2025-11-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_remove_cartitem_lab_test_remove_cartitem_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(choices=[('lab_test', 'Lab Test'), ('profile', 'Profile'), ('package', 'Package')], default='lab_test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_type', 'product_id')},
        ),
    ]
