# Generated by Django 5.2.6 on 2025-11-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_time_slot',
            field=models.CharField(blank=True, help_text="Example: '6-8 AM', '10-12 AM', or custom text", max_length=50, null=True),
        ),
    ]
