# Generated by Django 5.2.6 on 2025-12-15 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_remove_booking_scheduled_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='current_agent',
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='All users associated with this booking (agent, manager, dietitian, etc.)', related_name='booking_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
