# Generated by Django 5.2.6 on 2025-12-15 17:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_remove_booking_current_agent_booking_assigned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
