# Generated by Django 5.2.6 on 2026-01-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_booking_initial_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('verified', 'Verified'), ('root_manager', 'Root Manager'), ('feild_agent_assigned', 'Feild Agent Assigned'), ('payment_collected', 'Payment Collected'), ('sample_collected', 'Sample Collected'), ('report_uploaded', 'Report Uploaded'), ('health_manger_assigned', 'Health Manger Assigned'), ('dietitian_assigned', 'Dietitian Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=30),
        ),
    ]
