# Generated by Django 5.2.6 on 2025-09-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('message', models.TextField(help_text='Template text. Use placeholders like {otp} or {name}')),
                ('sender_name', models.CharField(default='DPATHC', max_length=20)),
                ('sms_type', models.CharField(default='TRANS', max_length=20)),
                ('peid', models.CharField(max_length=50)),
                ('template_id', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
