# Generated by Django 5.2.6 on 2025-12-30 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_enquiry_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='agent',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, related_name='agent_enquiry', to=settings.AUTH_USER_MODEL),
        ),
    ]
