# Generated by Django 5.2.6 on 2026-01-26 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_pushdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushdevice',
            old_name='token',
            new_name='expo_push_token',
        ),
        migrations.RenameField(
            model_name='pushdevice',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
